names3 <- c('The rate of snow accumulation [kg m^{-2} s^{-1}]',
            'Solar radiation flux at the surface [W m^{-2}]',
            'Long-wave radiation flux from the atmosphere [W m^{-2}]',
            'Height above the lake surface where the wind speed is measured [m]',
            'Height where temperature and humidity are measured [m]',
            'Wind speed at z=height_u_in [m s^{-1}]',
            'Air temperature at z=height_tq_in [K]',
            'Air specific humidity at z=height_tq_in',
            'Surface air pressure [N m^{-2} = kg m^{-1} s^{-2}]'
            )
names2 <- c('Temperature at the air-snow interface [K]',
            'Temperature at the snow-ice or air-ice interface [K]',
            'Mean temperature of the water column [K]',
            'Mixed-layer temperature [K]',
            'Temperature at the water-bottom sediment interface [K]',
            'Temperature at the bottom of the upper layer of the sediments [K]',
            'Shape factor (thermocline)',
            'Snow thickness [m]',
            'Ice thickness [m]',
            'Thickness of the mixed-layer [m]',
            'Thickness of the upper layer of bottom sediments [m]',
            'Updated surface temperature [K]',
            'Momentum flux [N m^{-2}]',               
            'Sensible heat flux [W m^{-2}]',          
            'Latent heat flux [W m^{-2}]',
            'Flux of water vapour [kg m^{-2} s^{-1}]',
            'Heat flux through the air-snow interface [W m^{-2}]',                    
            'Heat flux through the snow-ice or air-ice interface [W m^{-2}]',          
            'Heat flux through the ice-water or air-water interface [W m^{-2}] (net)',       
            'Heat flux through the water-bottom sediment interface [W m^{-2}]',        
            'Radiation flux at the lower boundary of the atmosphere [W m^{-2}]',      
            ## --- i.e. the incident radiation flux with no regard for the surface albedo  
            'Radiation flux through the air-snow interface [W m^{-2}]',                
            'Radiation flux through the snow-ice or air-ice interface [W m^{-2}]',     
            'Radiation flux through the ice-water or air-water interface [W m^{-2}]',  
            'Radiation flux through the mixed-layer-thermocline interface [W m^{-2}]', 
            'Radiation flux through the water-bottom sediment interface [W m^{-2}]',
            'Heat flux through the ice-water or air-water interface [W m^{-2}] (from water)',
            'Albedo snow',
            'Albedo ice',
            'Albedo water',
            'Radiation reflected on snow',
            'Radiation reflected on ice',
            'Radiation reflected on water'
            )
fullnames <- c(paste('Input:\n', names3),
               paste('Output:\n', names2))
